export const SUBJECT_MAP: { [key: string]: string } = {
  // 大學科目
  'uni-math': '大學數學',
  'uni-physics': '大學物理',
  'uni-chemistry': '大學化學',
  'uni-biology': '大學生物',
  'uni-engineering': '大學工程',
  'uni-business': '大學商科',
  'uni-economics': '大學經濟',
  'uni-accounting': '大學會計',
  'uni-finance': '大學金融',
  'uni-law': '大學法律',
  'uni-medicine': '大學醫學',
  'uni-nursing': '大學護理',
  'uni-psychology': '大學心理學',
  'uni-sociology': '大學社會學',
  'uni-education': '大學教育',
  'uni-arts': '大學文學',
  'uni-design': '大學設計',
  'uni-music': '大學音樂',
  'uni-computer-science': '大學電腦科學',
  'uni-thesis': '大學論文指導',
  'uni-calculus': '大學微積分',
  'uni-statistics': '大學統計',
  'uni-research': '研究方法',
  'uni-programming': '大學編程',
  'uni-language': '大學語言',
  
  // 中學科目
  'secondary-chinese': '中學中文',
  'secondary-english': '中學英文',
  'secondary-math': '中學數學',
  'secondary-ls': '通識教育',
  'secondary-physics': '物理',
  'secondary-chemistry': '化學',
  'secondary-biology': '生物',
  'secondary-economics': '經濟',
  'secondary-geography': '地理',
  'secondary-history': '歷史',
  'secondary-chinese-history': '中國歷史',
  'secondary-bafs': '企會財',
  'secondary-ict': '資訊與通訊科技',
  'secondary-integrated-science': '綜合科學',
  'secondary-dse': 'DSE總溫習',
  
  // 小學科目
  'primary-chinese': '小學中文',
  'primary-english': '小學英文',
  'primary-math': '小學數學',
  'primary-general': '常識',
  'primary-mandarin': '普通話',
  'primary-stem': 'STEM',
  
  // 興趣班
  'interest-art': '繪畫',
  'interest-music': '音樂',
  'interest-dance': '舞蹈',
  'interest-drama': '戲劇',
  'interest-programming': '編程',
  'interest-foreign-language': '外語',
  'interest-magic-chess': '魔術／棋藝',
  'interest-photography': '攝影',
  
  // 其他
  'other': '其他科目'
}; 